import { VisitorProfile } from "../../../assets";

export const visitors = [
  {
    // ID: 1,
    VisitorName: "Super Mart of the West",
    companyName: "Bentonville",
    profile: VisitorProfile,
    address: "Surat,Gujarat",
    meetingWith: "Will be meeting to Rani Patel",
    meetingTime: "At 11 p.m.",
    deatils: "Discussion about the upcoming project Carrying Laptop",
  },
  {
    VisitorName: "Electronics Depot",
    companyName: "Atlanta",
    profile: VisitorProfile,
    address: "Surat,Gujarat",
    meetingWith: "Will be meeting to Rani Patel",
    meetingTime: "At 11 p.m.",
    deatils: "Discussion about the upcoming project Carrying Laptop",
  },
  {
    VisitorName: "K&S Music",
    companyName: "Minnesota",
    profile: VisitorProfile,
    address: "Surat,Gujarat",
    meetingWith: "Will be meeting to Rani Patel",
    meetingTime: "At 11 p.m.",
    deatils: "Discussion about the upcoming project Carrying Laptop",
  },
  {
    VisitorName: "Tom's Club",
    companyName: "Issaquah",
    profile: VisitorProfile,
    address: "Surat,Gujarat",
    meetingWith: "Will be meeting to Rani Patel",
    meetingTime: "At 11 p.m.",
    deatils: "Discussion about the upcoming project Carrying Laptop",
  },
  {
    VisitorName: "E-Mart",
    companyName: "Hoffman Estates",
    profile: VisitorProfile,
    address: "Surat,Gujarat",
    meetingWith: "Will be meeting to Rani Patel",
    meetingTime: "At 11 p.m.",
    deatils: "Discussion about the upcoming project Carrying Laptop",
  },
  {
    VisitorName: "Walters",
    companyName: "Deerfield",
    profile: VisitorProfile,
    address: "Surat,Gujarat",
    meetingWith: "Will be meeting to Rani Patel",
    meetingTime: "At 11 p.m.",
    deatils: "Discussion about the upcoming project Carrying Laptop",
  },
  {
    VisitorName: "StereoShack",
    companyName: "Fort Worth",
    profile: VisitorProfile,
    address: "Surat,Gujarat",
    meetingWith: "Will be meeting to Rani Patel",
    meetingTime: "At 11 p.m.",
    deatils: "Discussion about the upcoming project Carrying Laptop",
  },
  {
    VisitorName: "Circuit Town",
    companyName: "Oak Brook",
    profile: VisitorProfile,
    address: "Surat,Gujarat",
    meetingWith: "Will be meeting to Rani Patel",
    meetingTime: "At 11 p.m.",
    deatils: "Discussion about the upcoming project Carrying Laptop",
  },
  {
    VisitorName: "Premier Buy",
    companyName: "Richfield",
    profile: VisitorProfile,
    address: "Surat,Gujarat",
    meetingWith: "Will be meeting to Rani Patel",
    meetingTime: "At 11 p.m.",
    deatils: "Discussion about the upcoming project Carrying Laptop",
  },
];
