export const customers = [
  {
    ID: 1,
    VisitorName: "Super Mart of the West",
    status: "Check Out",
    companyName: "Bentonville",
    state: "Approved",
    AddedBy: "Company",
  },
  {
    ID: 2,
    VisitorName: "Electronics Depot",
    status: "none",
    companyName: "Atlanta",
    state: "Pending",
    AddedBy: "Company",
  },
  {
    ID: 3,
    VisitorName: "K&S Music",
    status: "none",
    companyName: "Minnesota",
    state: "Rejected",
    AddedBy: "Company",
  },
  {
    ID: 4,
    VisitorName: "Tom's Club",
    status: "Check in",
    companyName: "Issaquah",
    state: "Approved",
    AddedBy: "External",
  },
  {
    ID: 5,
    VisitorName: "E-Mart",
    status: "none",
    companyName: "Hoffman Estates",
    state: "Pending",
    AddedBy: "Company",
  },
  {
    ID: 6,
    VisitorName: "Walters",
    status: "none",
    companyName: "Deerfield",
    state: "Rejected",
    AddedBy: "Company",
  },
  {
    ID: 7,
    VisitorName: "StereoShack",
    status: "Check in",
    companyName: "Fort Worth",
    state: "Approved",
    AddedBy: "External",
  },
  {
    ID: 8,
    VisitorName: "Circuit Town",
    status: "none",
    companyName: "Oak Brook",
    state: "Pending",
    AddedBy: "Company",
  },
  {
    ID: 9,
    VisitorName: "Premier Buy",
    status: "none",
    companyName: "Richfield",
    state: "Rejected",
    AddedBy: "External",
  },
  {
    ID: 10,
    VisitorName: "ElectrixMax",
    status: "Check Out",
    companyName: "Naperville",
    state: "Approved",
    AddedBy: "Company",
  },
  {
    ID: 11,
    VisitorName: "Video Emporium",
    status: "none",
    companyName: "Dallas",
    state: "Pending",
    AddedBy: "External",
  },
  {
    ID: 12,
    VisitorName: "Screen Shop",
    status: "none",
    companyName: "Mooresville",
    state: "Rejected",
    AddedBy: "External",
  },
];
